### ISSUE TITLE
Buggy test file: test_file_storage

### ISSUE THREAD

**Issue by reunicorn1** [Abdallah-Abdelrahman/AirBnB_clone#3]
the file test_file_storage has some bugs which prevents the full test suite to be executed, and it is still under construction

**Comment by Abdallah-Abdelrahman** [comment]
can you elaborate on the problem w/  example

**Comment by reunicorn1** [comment]
All related bugs, were either related to misusage of some certain methods, typos, or missing imported modules (datetime). But they're all fixed now
